apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- bluegreen-rollout.yaml
- bluegreen-service.yaml
- bluegreen-service-preview.yaml
- bluegreen-smoke-test.yaml

namespace: staging
images:
- name: ccr.ccs.tencentyun.com/shovel/shovel-rollouts
  newTag: 0.0.2