apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: saken-manual
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: saken-manual
  template:
    metadata:
      labels:
        app:  saken-manual
    spec:
      containers:
      - name:  saken-manual
        image:  ccr.ccs.tencentyun.com/shovel/shovel-rollouts:0.0.2
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
        livenessProbe:
          httpGet:
            path: /ping
            port: 9099
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 9099
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  9099
          name:  saken-manual