apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: canary-success-rate
    interval: 5m
    successCondition: result[0] >= 0.9
    failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus.kube-ops.svc.cluster.local
        query: |
          sum(irate(gin_metric_handler_http_responses_status_total{code = "200",kubernetes_name = "{{args.service-name}}"}[5m])) /
          sum(irate(gin_metric_handler_http_responses_status_total{kubernetes_name = "{{args.service-name}}"}[5m]))