apiVersion: v1
kind: Service
metadata:
  name: saken-canary-lb
  namespace: default
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"
spec:
  selector:
    app: saken-canary
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: saken-canary
    protocol: TCP
    port: 80
    targetPort: 9099