apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- canary-rollout.yaml
- canary-service.yaml
- canary-success-rate.yaml

namespace: staging
images:
- name: ccr.ccs.tencentyun.com/shovel/shovel-rollouts
  newTag: 0.0.2